trigger:
- master
- create-odata-cli-pipeline

name: 'OData CLI'

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  rootDir: '$(Build.SourcesDirectory)'
  sln: '$(rootDir)\OData.Cli.sln'
  signigConfigPath: '$(rootDir)\configs'
  signingConfigFiles: '*.*'
  productBinPath: '$(rootDir)\src\Microsoft.OData.Cli\bin\$(BuildConfiguration)'
  productFiles: 'odata-cli.*?(*.dll|*.config|*.pdb)'
  nupkgPath: '$(Build.ArtifactStagingDirectory)'
  nupkgFile: 'odata-cli.0.1.0.nupkg'
  signingFiles: 'odata-cli.dll'
  mainDll: 'odata-cli.dll'
  snExe: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\sn.exe'
  snExe64: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe'

stages:
- stage: Build

  jobs:
  - job: Build
    steps:

    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '>=5.2.0'

    - task: NuGetCommand@2
      displayName: 'Nuget restore - OData.Cli.sln'
      inputs:
        restoreSolution: '$(sln)'

    - task: VSBuild@1
      displayName: 'Build solution - OData.Cli.sln'
      inputs:
        solution: '$(sln)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - publish: configs
      displayName: Publish Signing Scripts
      artifact: configs

    - task: DotNetCoreCLI@2
      displayName: 'Publish OData Cli'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Microsoft.OData.Cli/Microsoft.OData.Cli.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)\pub'

   - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact - Publish output'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\pub'
        ArtifactName: PublishedCli
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact - Nupkg'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\Nupkg'
        ArtifactName: 'Nupkg'
        publishLocation: 'Container'
  

